server:
  port: 8081
  
spring:
  application:
    name: auth-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true
    hibernate:
      ddl-auto: none

batch:
   path:
     config: D:/GIT/ImporveSkillProject/ASProject/ASBackend/batch-config.properties