server:
  port: 8081
  
spring:
  application:
    name: auth-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true

batch:
   path:
     config: D:/Test/batch-config.properties