server:
  port: 8084

spring:
  application:
    name: debt-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true
         use_get_generated_keys: true

batch:
   path:
     config: D:/Test/batch-config.properties
