server:
  port: 8087
spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    group-id: payment-group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    auto-offset-reset: earliest
batch:
   path:
     config: D:/Test/batch-config.properties