server:
  port: 8082
spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
batch:
   path:
     config: D:/Test/batch-config.properties