server:
  port: 8082
  
spring:
  application:
    name: account-service
  jpa:
    show-sql: true
    properties:
      hibernate:
         format_sql: true

batch:
   path:
     config: D:/Test/batch-config.properties